default_language_version:
  python: python3.9

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    exclude: "anime_ml/data"
  - id: check-json
    exclude: "anime_ml/data"
  - id: check-merge-conflict
  - id: check-toml
  - id: detect-private-key
  - id: debug-statements
  - id: name-tests-test

- repo: local
  hooks:
  - id: black
    name: black
    stages: [commit]
    language: system
    entry: black -l 120
    types: [python]
    pass_filenames: false
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: isort
    types: [python]
    pass_filenames: true
